const Types = {
    SET_REACTANT: 'SET_REACTANT',

    SET_NUM_REACTANTS: 'SET_NUM_REACTANTS',
    SET_NUM_PRODUCTS: 'SET_NUM_PRODUCTS',
    SET_NUM_DILUENTS: 'SET_NUM_DILUENTS',
}

export default Types